/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotRouteImport } from './routes/bot'
import { Route as ApiCronLoopRouteImport } from './routes/api/cron.loop'
import { Route as ApiDemoPaystackRouteImport } from './routes/api/demo.paystack'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks.paystack'
import { Route as ApiWebhooksTelegramRouteImport } from './routes/api/webhooks.telegram'
import { Route as ApiFxRouteImport } from './routes/api/fx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronLoopRoute = ApiCronLoopRouteImport.update({
  id: '/api/cron/loop',
  path: '/api/cron/loop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoPaystackRoute = ApiDemoPaystackRouteImport.update({
  id: '/api/demo/paystack',
  path: '/api/demo/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTelegramRoute = ApiWebhooksTelegramRouteImport.update({
  id: '/api/webhooks/telegram',
  path: '/api/webhooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRoute = ApiFxRouteImport.update({
  id: '/api/fx',
  path: '/api/fx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/api/cron/loop': typeof ApiCronLoopRoute
  '/api/demo/paystack': typeof ApiDemoPaystackRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/api/fx': typeof ApiFxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/api/cron/loop': typeof ApiCronLoopRoute
  '/api/demo/paystack': typeof ApiDemoPaystackRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/api/fx': typeof ApiFxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/api/cron/loop': typeof ApiCronLoopRoute
  '/api/demo/paystack': typeof ApiDemoPaystackRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/api/fx': typeof ApiFxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bot'
    | '/api/cron/loop'
    | '/api/demo/paystack'
    | '/api/webhooks/paystack'
    | '/api/webhooks/telegram'
    | '/api/fx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bot'
    | '/api/cron/loop'
    | '/api/demo/paystack'
    | '/api/webhooks/paystack'
    | '/api/webhooks/telegram'
    | '/api/fx'
  id:
    | '__root__'
    | '/'
    | '/bot'
    | '/api/cron/loop'
    | '/api/demo/paystack'
    | '/api/webhooks/paystack'
    | '/api/webhooks/telegram'
    | '/api/fx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotRoute: typeof BotRoute
  ApiCronLoopRoute: typeof ApiCronLoopRoute
  ApiDemoPaystackRoute: typeof ApiDemoPaystackRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
  ApiWebhooksTelegramRoute: typeof ApiWebhooksTelegramRoute
  ApiFxRoute: typeof ApiFxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/loop': {
      id: '/api/cron/loop'
      path: '/api/cron/loop'
      fullPath: '/api/cron/loop'
      preLoaderRoute: typeof ApiCronLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/paystack': {
      id: '/api/demo/paystack'
      path: '/api/demo/paystack'
      fullPath: '/api/demo/paystack'
      preLoaderRoute: typeof ApiDemoPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/telegram': {
      id: '/api/webhooks/telegram'
      path: '/api/webhooks/telegram'
      fullPath: '/api/webhooks/telegram'
      preLoaderRoute: typeof ApiWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx': {
      id: '/api/fx'
      path: '/api/fx'
      fullPath: '/api/fx'
      preLoaderRoute: typeof ApiFxRouteImport
      parentRoute: typeof rootRouteImport
    }

  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotRoute: BotRoute,
  ApiCronLoopRoute: ApiCronLoopRoute,
  ApiDemoPaystackRoute: ApiDemoPaystackRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
  ApiWebhooksTelegramRoute: ApiWebhooksTelegramRoute,
  ApiFxRoute: ApiFxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
